name: Update High Scores
on:
  issues:
    types: [opened]
jobs:
  update-scores:
    if: contains(github.event.issue.title, 'HIGHSCORE')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v3
      - name: Process score submission
        run: |
          # Extract score information from issue body
          SCORE_DATA=$(echo '${{ github.event.issue.body }}' | grep -oP '(?<=```json).*(?=```)' | tr -d '\n')
          PLAYER_NAME=$(echo $SCORE_DATA | jq -r '.playerName')
          SCORE=$(echo $SCORE_DATA | jq -r '.score')
          
          # Validate score data
          if [[ -z "$PLAYER_NAME" || -z "$SCORE" ]]; then
            echo "Invalid score data"
            exit 1
          fi
          
          # Add score to highscores.json
          jq --arg name "$PLAYER_NAME" --arg score "$SCORE" --arg timestamp "$(date +%s)" \
            '.scores += [{"playerName": $name, "score": ($score|tonumber), "timestamp": ($timestamp|tonumber)}] | .scores = (.scores | sort_by(-.score) | .[0:10])' \
            highscores.json > highscores.tmp
          mv highscores.tmp highscores.json
          
          # Commit and push changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add highscores.json
          git commit -m "Update high scores for $PLAYER_NAME"
          git push
          
      - name: Close issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: "Score recorded! The high scores have been updated."